docs/node-model.md: Translate to Bengali
gatsbyjs/gatsby-bn pull request #16
Opened 2020-04-23 03:32 UTC by ayan-b

Related to https://github.com/gatsbyjs/gatsby-bn/issues/1

2020-04-23 12:44 UTC, shakib609 requested changes

2020-04-23 12:44 UTC, shakib609 commented on docs/docs/node-model.md
> +Gatsby তার অভ্যন্তরীণ ডেটা স্টোর এবং ক্যোয়ারী ক্ষমতা GraphQL ফিল্ড রিসোলভারগুলিকে `context.nodeModel`-তে প্রকাশ করে।
```suggestion
Gatsby তার অভ্যন্তরীণ ডেটা স্টোর এবং ক্যোয়ারী ক্ষমতা GraphQL ফিল্ড রিসোলভারগুলিকে `context.nodeModel`-এ প্রকাশ করে।
```

2020-04-23 12:51 UTC, ayan-b commented on docs/docs/node-model.md
> +Gatsby তার অভ্যন্তরীণ ডেটা স্টোর এবং ক্যোয়ারী ক্ষমতা GraphQL ফিল্ড রিসোলভারগুলিকে `context.nodeModel`-তে প্রকাশ করে।
Done.

2020-04-23 17:24 UTC, shakib609 submitted a review, later dismissed

2020-04-25 03:55 UTC, nutboltu commented on docs/docs/node-model.md
> +description: এই ডকুমেন্টেশনটি Gatsby-র GraphQL ডেটা লেয়ার নোডগুলির মডেল ব্যাখ্যা করে
লেয়ার নোডগুলির মডেল ব্যাখ্যা করে =>  লেয়ারের নোড মডেলগুলিকে ব্যাখ্যা করে

2020-04-25 03:55 UTC, nutboltu commented on docs/docs/node-model.md
> +Gatsby তার অভ্যন্তরীণ ডেটা স্টোর এবং ক্যোয়ারী ক্ষমতা GraphQL ফিল্ড রিসোলভারগুলিকে `context.nodeModel`-এ প্রকাশ করে।
```suggestion
 `context.nodeModel` এর মাধ্যমে Gatsby  তার অভ্যন্তরীণ ডেটা স্টোর এবং ক্যোয়ারী ক্ষমতাকে GraphQL ফিল্ড রিসোলভারগুলোতে প্রকাশ করে।
```

2020-04-25 03:55 UTC, nutboltu commented on docs/docs/node-model.md
> +## ব্যবহারের উদাহরণ
Let's make it simple, `উদাহরণ`

2020-04-25 04:58 UTC, ayan-b commented on docs/docs/node-model.md
> +description: এই ডকুমেন্টেশনটি Gatsby-র GraphQL ডেটা লেয়ার নোডগুলির মডেল ব্যাখ্যা করে
Done,

2020-04-25 04:58 UTC, ayan-b commented on docs/docs/node-model.md
> +## ব্যবহারের উদাহরণ
Done.

2020-04-25 04:58 UTC, ayan-b commented on docs/docs/node-model.md
> +## ব্যবহারের উদাহরণ
Done.

2020-04-25 05:01 UTC, ayan-b commented on docs/docs/node-model.md
> +Gatsby তার অভ্যন্তরীণ ডেটা স্টোর এবং ক্যোয়ারী ক্ষমতা GraphQL ফিল্ড রিসোলভারগুলিকে `context.nodeModel`-এ প্রকাশ করে।
Done.

2020-04-25 05:07 UTC, nutboltu approved these changes
Thanks for addressing quickly

2020-04-25 05:07 UTC, merged