docs/browser-apis.md: Translate to Bengali
gatsbyjs/gatsby-bn pull request #19
Opened 2020-04-24 03:55 UTC by ayan-b

Related to #1

2020-04-24 13:08 UTC, shakib609 requested changes

2020-04-24 13:08 UTC, shakib609 commented on docs/docs/browser-apis.md
>  ## Usage
ব্যবহারবিধি

2020-04-24 13:14 UTC, ayan-b commented on docs/docs/browser-apis.md
>  ## Usage
Done.

2020-04-24 16:30 UTC, shakib609 approved these changes

2020-04-25 04:03 UTC, nutboltu approved these changes

2020-04-25 04:03 UTC, merged