node.md initial translation updated
gatsbyjs/gatsby-bn pull request #24
Opened 2020-06-03 15:46 UTC by khodarkhashi

2020-06-09 13:19 UTC, shakib609 requested changes
There are some MacOS specific files with the PR which are not related. Also, the line number of the English version is 34 whereas the translated version is 40.

2020-06-09 13:19 UTC, shakib609 commented on docs/docs/glossary/node.md
Extra newline

2020-06-09 13:19 UTC, shakib609 commented on docs/docs/glossary/node.md
> +Node.js সম্পর্কে আরও জানুন , এটি অন্যতম একটি সফটওয়ার প্যাকেজ যা Gatsby কে সম্ভব করেছে।
সফটওয়্যার

2020-06-09 13:19 UTC, shakib609 commented on docs/docs/glossary/node.md
> +Node.js  একটি জাভাস্ক্রিপ্ট রানটাইম। গুগল ক্রোম যে ইঞ্জিন ব্যবহার করে সেই একই ইঞ্জিন ব্যবহার করে Node.js । Node.js এর মাধ্যমে আপনি কোন ওয়েব ব্রাউজার ছাড়াই জাভাস্ক্রিপ্ট এপ্লিকেশান চালাতে পারবেন।
এপ্লিকেশন

2020-06-10 04:12 UTC, nutboltu requested changes

2020-06-10 04:12 UTC, nutboltu commented on docs/docs/glossary/node.md
> +Node.js  একটি জাভাস্ক্রিপ্ট রানটাইম। গুগল ক্রোম যে ইঞ্জিন ব্যবহার করে সেই একই ইঞ্জিন ব্যবহার করে Node.js । Node.js এর মাধ্যমে আপনি কোন ওয়েব ব্রাউজার ছাড়াই জাভাস্ক্রিপ্ট এপ্লিকেশন চালাতে পারবেন।
nit: double space before `একটি জাভাস্ক্রিপ্ট রানটাইম`

2020-06-10 04:12 UTC, nutboltu commented on docs/docs/glossary/node.md
> +আপনি একবার Node.js ইন্সটল করে ফেললে [command line](/docs/glossary#command-line) থেকে জাভাস্ক্রিপ্ট সম্পাদন করতে পারবেন। আপনি একটি ইন্টারেকটিভ শেলে 'node' টাইপ করুন। যে জাভাস্ক্রিপ্ট ফাইলটি আপনি সম্পা
'node' -> `node`. 
'node /Users/gatsbyfan/hello-world.js' -> `node /Users/gatsbyfan/hello-world.js`
Please use grave accent(`) instead of  single quote(')

command line -> কমান্ড লাইন

2020-06-10 04:12 UTC, nutboltu commented on docs/docs/glossary/node.md
> +Gatsby ব্যবহারের পূর্বে আপনাকে Node.js ইন্সটল করে নিতে হবে [install Node.js](/tutorial/part-zero/#-install-nodejs-and-npm) Gatsby জাভাস্ক্রিপ্ট দিয়ে তৈরি এবং এর জন্য Node.js রানটাইম প্রয়োজন হয়।
Please change the URL. `/tutorial/part-zero/#-install-nodejs-and-npm` is deprecated.

2020-06-10 04:12 UTC, nutboltu commented on docs/docs/glossary/node.md
> +Gatsby ব্যবহারের পূর্বে আপনাকে Node.js ইন্সটল করে নিতে হবে [install Node.js](/tutorial/part-zero/#-install-nodejs-and-npm) Gatsby জাভাস্ক্রিপ্ট দিয়ে তৈরি এবং এর জন্য Node.js রানটাইম প্রয়োজন হয়।
```suggestion
Gatsby ব্যবহারের পূর্বে আপনাকে [Node.js ইন্সটল](/tutorial/part-zero/#install-nodejs-for-your-appropriate-operating-system) করে নিতে হবে। Gatsby জাভাস্ক্রিপ্ট দিয়ে তৈরি এবং এর জন্য Node.js রানটাইম প্রয়োজন হয়। 
```

2020-06-10 04:12 UTC, nutboltu commented on docs/docs/glossary/node.md
> +Node.js ইন্সটল করলে তার সাথে [npm](/docs/glossary#npm), (Node.js এর প্যাকেজ ম্যানেজার) ও ইন্সটল হয়। প্যাকেজ ম্যানেজার এক ধরনের বিশেষ সফটওয়ার যা আপনার প্রোজেক্টে ব্যবহৃত বিভিন্ন মডিউল এবং প্যাকেজ আপডে
```suggestion
Node.js ইন্সটল করলে তার সাথে [npm](/docs/glossary#npm) ইন্সটল হয়,  যা Node.js এর _প্যাকেজ ম্যানেজার_ । প্যাকেজ ম্যানেজার এক ধরনের বিশেষ সফটওয়ার যা আপনার প্রোজেক্টে ব্যবহৃত বিভিন্ন মডিউল ও প্যাকেজ আপডেট এবং  ইন্সটল করে দেয়।  
```

2020-06-10 04:12 UTC, nutboltu commented on docs/docs/glossary/node.md
> +আপনি Gatsby এবং এর উপর নির্ভর করে এমন সবকিছু ইন্সটল করার জন্য npm ব্যবহার করবেন। Gatsby কমান্ড লাইন ইন্টারফেইস অথবা CLI ইন্সটল করার জন্য কমান্ড লাইন হিসেবে টাইপ করুন 'npm install -g gatsby-cli' । '-g
নির্ভর করে -> নির্ভরশীল।
Please use grave accent(`) instead of  single quote(')

2020-06-10 04:12 UTC, nutboltu commented on docs/docs/glossary/node.md
> +- [Node.js](https://nodejs.org/en/) অফিসিয়াল ওয়েবসাইট।
No `|` after ওয়েবসাইট. Same goes to following links

2020-06-10 05:32 UTC, nutboltu submitted a review, later dismissed
LGTM @shakib609 would please take a look again?

2020-06-10 11:58 UTC, shakib609 requested changes
Some minor formatting issues need to be fixed.

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +## Node.js কি?
```suggestion
## Node.js কি?
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +Node.js একটি জাভাস্ক্রিপ্ট রানটাইম। গুগল ক্রোম যে ইঞ্জিন ব্যবহার করে সেই একই ইঞ্জিন ব্যবহার করে Node.js । Node.js এর মাধ্যমে আপনি কোন ওয়েব ব্রাউজার ছাড়াই জাভাস্ক্রিপ্ট এপ্লিকেশন চালাতে পারবেন।
```suggestion
Node.js একটি জাভাস্ক্রিপ্ট রানটাইম। গুগল ক্রোম যে ইঞ্জিন ব্যবহার করে সেই একই ইঞ্জিন ব্যবহার করে Node.js । Node.js এর মাধ্যমে আপনি কোন ওয়েব ব্রাউজার ছাড়াই জাভাস্ক্রিপ্ট এপ্লিকেশন চালাতে পারবেন।
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +২০০০ এর শুরুর দিকে জিমেইল এবং ফ্লিকার এর মত সার্ভিস আমাদের দেখিয়েছিল জাভাস্ক্রিপ্ট শক্তিশালী এবং ত্রুটিমুক্ত এপ্লিকেশন তৈরির কাজের ব্যবহার হতে পারে যেগুলো ওয়েব ব্রাউজার এবং ইন্টারনেট কানেকশন আছে এমন
```suggestion
২০০০ এর শুরুর দিকে জিমেইল এবং ফ্লিকার এর মত সার্ভিস আমাদের দেখিয়েছিল জাভাস্ক্রিপ্ট শক্তিশালী এবং ত্রুটিমুক্ত এপ্লিকেশন তৈরির কাজের ব্যবহার হতে পারে যেগুলো ওয়েব ব্রাউজার এবং ইন্টারনেট কানেকশন আছে এমন যে কারো জন্য সহজলভ্য।
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +পরের বছর একটি স্বতন্ত্র জাভাস্ক্রিপ্ট রানটাইম হিসেবে Node.js এর অভিষেক ঘটে যা কিনা V8 ইঞ্জিন ব্যবহার করত।
```suggestion
পরের বছর একটি স্বতন্ত্র জাভাস্ক্রিপ্ট রানটাইম হিসেবে Node.js এর অভিষেক ঘটে যা কিনা V8 ইঞ্জিন ব্যবহার করত।
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +আপনি একবার Node.js ইন্সটল করে ফেললে [কমান্ড লাইন](/docs/glossary#command-line) থেকে জাভাস্ক্রিপ্ট সম্পাদন করতে পারবেন। আপনি একটি ইন্টারেকটিভ শেলে `node` টাইপ করুন। যে জাভাস্ক্রিপ্ট ফাইলটি আপনি সম্পাদ
```suggestion
আপনি একবার Node.js ইন্সটল করে ফেললে [কমান্ড লাইন](/docs/glossary#command-line) থেকে জাভাস্ক্রিপ্ট সম্পাদন করতে পারবেন। আপনি একটি ইন্টারেকটিভ শেলে `node` টাইপ করুন। যে জাভাস্ক্রিপ্ট ফাইলটি আপনি সম্পাদন করতে চান তার পাথ 'node' কমান্ডের সাথে যোগ করে দিন। উদাহরণ - `node /Users/gatsbyfan/hello-world.js`।
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +Gatsby ব্যবহারের পূর্বে আপনাকে [Node.js ইন্সটল](/tutorial/part-zero/#install-nodejs-for-your-appropriate-operating-system) করে নিতে হবে। Gatsby জাভাস্ক্রিপ্ট দিয়ে তৈরি এবং এর জন্য Node.js রানটাইম প্র
```suggestion
Gatsby ব্যবহারের পূর্বে আপনাকে [Node.js ইন্সটল](/tutorial/part-zero/#install-nodejs-for-your-appropriate-operating-system) করে নিতে হবে। Gatsby জাভাস্ক্রিপ্ট দিয়ে তৈরি এবং এর জন্য Node.js রানটাইম প্রয়োজন হয়।
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +Node.js ইন্সটল করলে তার সাথে [npm](/docs/glossary#npm) ইন্সটল হয়,  যা Node.js এর _প্যাকেজ ম্যানেজার_। প্যাকেজ ম্যানেজার এক ধরনের বিশেষ সফটওয়ার যা আপনার প্রোজেক্টে ব্যবহৃত বিভিন্ন মডিউল ও প্যাকেজ আপডে
```suggestion
Node.js ইন্সটল করলে তার সাথে [npm](/docs/glossary#npm) ইন্সটল হয়,  যা Node.js এর _প্যাকেজ ম্যানেজার_। প্যাকেজ ম্যানেজার এক ধরনের বিশেষ সফটওয়ার যা আপনার প্রোজেক্টে ব্যবহৃত বিভিন্ন মডিউল ও প্যাকেজ আপডেট এবং ইন্সটল করে দেয়।
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +আপনি Gatsby এবং এর উপর নির্ভরশীল এমন সবকিছু ইন্সটল করার জন্য npm ব্যবহার করবেন। Gatsby কমান্ড লাইন ইন্টারফেইস অথবা CLI ইন্সটল করার জন্য কমান্ড লাইন হিসেবে টাইপ করুন `npm install -g gatsby-cli` । `-g`
```suggestion
আপনি Gatsby এবং এর উপর নির্ভরশীল এমন সবকিছু ইন্সটল করার জন্য npm ব্যবহার করবেন। Gatsby কমান্ড লাইন ইন্টারফেইস অথবা CLI ইন্সটল করার জন্য কমান্ড লাইন হিসেবে টাইপ করুন `npm install -g gatsby-cli` । `-g` ফ্ল্যাগটি গ্লোবালি Gatsby ইন্সটল করে। এর মানে আপনি কমান্ড লাইনে gatsby লিখেই এটি ব্যবহার করতে পারবেন। উদাহরণস্বরূপ - `gatsby new` টাইপ করে আপনি নতুন একটি Gatsby সাইট তৈরি করতে পারবেন।
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +## Node.js সম্পর্কে আরও জানুন
```suggestion
## Node.js সম্পর্কে আরও জানুন
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +- [Node.js](https://nodejs.org/en/) অফিসিয়াল ওয়েবসাইট
```suggestion
- [Node.js](https://nodejs.org/en/) অফিসিয়াল ওয়েবসাইট
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +- [Introduction to Node.js](https://nodejs.dev)
```suggestion
- [Introduction to Node.js](https://nodejs.dev)
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
> +- [NodeSchool](https://nodeschool.io/) অনলাইন এবং ব্যাক্তিগত Node.js ওয়ার্কশপ প্রদান করে
```suggestion
- [NodeSchool](https://nodeschool.io/) অনলাইন এবং ব্যাক্তিগত Node.js ওয়ার্কশপ প্রদান করে
```

2020-06-10 11:58 UTC, shakib609 commented on docs/docs/glossary/node.md
>  - [V8](https://v8.dev/) developer blog web site
```suggestion
- [V8](https://v8.dev/) ডেভেলপার ব্লগ ওয়েবসাইট
```

2020-06-10 14:12 UTC, shakib609 commented on docs/docs/glossary/node.md
> +- [Introduction to Node.js](https://nodejs.dev)
@khodarkhashi you missed some.

2020-06-10 15:08 UTC, shakib609 approved these changes

2020-06-10 15:09 UTC, merged