Translate tutorial/part-six
gatsbyjs/gatsby-bn pull request #26
Opened 2020-08-18 20:05 UTC by JubayerJoy

Signed-off-by: Jubayer Abdullah Joy <jubayerjoy98@gmail.com>

### Current State
- [x] Translation of `tutorial/part-six` complete 
#### Work in Progress
- [ ] Review
### Note for Reviewers
- Translation is complete, kept as close to original and same ammount of lines
Please Review 🚀

2020-08-18 20:06 UTC, JubayerJoy commented
@nutboltu, @shakib609 please review. Thanks! 🚀

2020-08-20 15:07 UTC, nutboltu requested changes
LGTM. minor changes requested.

2020-08-20 15:07 UTC, nutboltu commented on docs/tutorial/part-six/index.md
> +অনেক দারুণ লাগছে! আপনি মাত্রই একটা Index পেইজ তৈরি করেছেন যেখানে আপনি মার্কডাউন ফাইল্গুলো
ফাইল্গুলো -> ফাইলগুলো

2020-08-20 15:07 UTC, nutboltu commented on docs/tutorial/part-six/index.md
> +Query করছেন এবং একটি ব্লগপোস্টের টাইটেল এবং উদ্ধৃতাংশ (Excerpt) এর লিস্ট তৈরি করছেন। কিন্তু আপনি শুধু উদ্ধৃতাংশ চান না, আপনি মার্কডাউন ফাইলের আসল পেইজ চান।
Let's remove this extra (Excerpt)

2020-08-20 15:28 UTC, JubayerJoy commented on docs/tutorial/part-six/index.md
> +অনেক দারুণ লাগছে! আপনি মাত্রই একটা Index পেইজ তৈরি করেছেন যেখানে আপনি মার্কডাউন ফাইল্গুলো
Very good spot! Fixed, Thank you. 🎈

2020-08-20 15:30 UTC, JubayerJoy commented on docs/tutorial/part-six/index.md
> +Query করছেন এবং একটি ব্লগপোস্টের টাইটেল এবং উদ্ধৃতাংশ (Excerpt) এর লিস্ট তৈরি করছেন। কিন্তু আপনি শুধু উদ্ধৃতাংশ চান না, আপনি মার্কডাউন ফাইলের আসল পেইজ চান।
I was thinking the same vai, removed it vai! 👍

2020-08-21 01:13 UTC, nutboltu approved these changes
awesome! @JubayerJoy

2020-08-21 01:13 UTC, merged