Translated [working-with-starters.md] to Bengali
gatsbyjs/gatsby-bn pull request #38
Opened 2021-11-19 15:06 UTC by devgossips

:)

2021-11-19 15:08 UTC, devgossips commented
Related to #1

2021-11-19 15:10 UTC, devgossips commented
@shakib609 @nutboltu Please review and merge this pull request

2021-12-04 22:24 UTC, shakib609 requested changes

2021-12-04 22:24 UTC, shakib609 commented on docs/docs/recipes/working-with-starters.md
> +টেবিলঅফ বিষয়বস্তুর গভীরতা: 1
The `title` and the `tableOfContentsDepth` words should not be translated

2021-12-04 22:24 UTC, shakib609 commented on docs/docs/recipes/working-with-starters.md
> +[স্টার্টার](/docs/starters/) বয়লারপ্লেট গ্যাটসবি সাইটগুলি সরকারীভাবে বা সম্প্রদায় দ্বারা রক্ষণাবেক্ষণ করা হয়.
I don't think this is the correct/appropriate translation for the line.
We should use something more suitable for the words `officially` and `community`.

2021-12-04 22:24 UTC, shakib609 commented on docs/docs/recipes/working-with-starters.md
> +### স্টার্টার ব্যবহার করা
```suggestion
## স্টার্টার ব্যবহার করা
```

2021-12-04 22:24 UTC, shakib609 commented on docs/docs/recipes/working-with-starters.md
> +- [গ্যাটসবি সিএলআই](/docs/gatsby-cli) ইনস্টল করা হয়েছে।
```suggestion
- [গ্যাটসবি সিএলআই](/docs/gatsby-cli) ইনস্টল করা থাকতে হবে।
```

2021-12-04 22:24 UTC, shakib609 commented on docs/docs/recipes/working-with-starters.md
> +২. স্টার্টারের উপর ভিত্তি করে একটি নতুন সাইট তৈরি করুন। টার্মিনালে, চালান:
```suggestion
২. স্টার্টারের উপর ভিত্তি করে একটি নতুন সাইট তৈরি করুন। টার্মিনালে নিচের কমান্ডটি চালান:
```

2021-12-04 22:24 UTC, shakib609 commented on docs/docs/recipes/working-with-starters.md
> +### অতিরিক্ত সম্পদ
We should use something other than `সম্পদ` for `resources`

2021-12-04 22:24 UTC, shakib609 commented on docs/docs/recipes/working-with-starters.md
> +- গ্যাটসবি স্টার্টার ব্যবহার করার জন্য [আরও বিস্তারিত নির্দেশিকা](/docs/starters/) অনুসরণ করুন ।
```suggestion
- গ্যাটসবি স্টার্টার ব্যবহার করার জন্য [আরও বিস্তারিত নির্দেশিকা](/docs/starters/) অনুসরণ করুন।
```

2021-12-05 05:17 UTC, devgossips commented
Yes I have resolved all the issues @shakib609 please approve & merge the pr

2021-12-05 13:03 UTC, shakib609 commented
Hello @devgossips you did not change anything from the last commit. You have to make the changes in your branch and push it to github and then resolve the issues. Can you kindly look into that?

2021-12-06 03:23 UTC, devgossips commented
Finally updated @shakib609

2022-06-22 17:25 UTC, closed without merging